/// Flutter icons CatFont
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CatFont
///      fonts:
///       - asset: fonts/CatFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CatFont {
  CatFont._();

  static const _kFontFam = 'CatFont';
  static const _kFontPkg = null;

  static const IconData cat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData try_out = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
